# Generated by Django 2.1.3 on 2019-03-19 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупка',
            },
        ),
        migrations.CreateModel(
            name='GoTender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(verbose_name='Сумма:')),
                ('ques', models.IntegerField(default='', verbose_name='Колличество:')),
                ('phones', models.IntegerField(default='', verbose_name='Телефон:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name': 'Вступительная сумма',
                'verbose_name_plural': 'Вступительная сумма',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compania', models.TextField(default='', verbose_name='Организации:')),
                ('inn', models.IntegerField(default='', verbose_name='ИНН:')),
                ('kpp', models.IntegerField(default='', verbose_name='КПП:')),
                ('phone', models.IntegerField(default='', verbose_name='Телефон:')),
                ('title', models.TextField(max_length=500, verbose_name='Заголовок:')),
                ('text', models.TextField(max_length=1000, verbose_name='Описание:')),
                ('cost', models.IntegerField(verbose_name='Стоимость:')),
                ('que', models.IntegerField(default='', verbose_name='Колличество(Укажите 0 если не нужна такая инофрмация):')),
                ('region', models.CharField(max_length=100, verbose_name='Регион закупки:')),
                ('supply', models.CharField(max_length=100, verbose_name='Место поставки ')),
                ('start', models.DateField(verbose_name='Дата размещения:')),
                ('ending', models.DateField(verbose_name='Окончание приёма предложений:')),
                ('nameFile', models.FileField(upload_to='', verbose_name='Документы:')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор:')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендер',
            },
        ),
        migrations.AddField(
            model_name='gotender',
            name='tenders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Post', verbose_name='Тендер:'),
        ),
        migrations.AddField(
            model_name='buytender',
            name='tenders',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.Post', verbose_name='Тендер'),
        ),
    ]
